var searchData=
[
  ['abs_2ehpp_6310',['abs.hpp',['../d5/d5b/fwd_2fun_2abs_8hpp.html',1,'(Global Namespace)'],['../db/dba/prim_2fun_2abs_8hpp.html',1,'(Global Namespace)'],['../d4/da8/rev_2fun_2abs_8hpp.html',1,'(Global Namespace)']]],
  ['accumulate_5fadjoints_2ehpp_6311',['accumulate_adjoints.hpp',['../da/d3e/accumulate__adjoints_8hpp.html',1,'']]],
  ['accumulator_2ehpp_6312',['accumulator.hpp',['../dd/df7/fwd_2fun_2accumulator_8hpp.html',1,'(Global Namespace)'],['../d7/dcf/prim_2fun_2accumulator_8hpp.html',1,'(Global Namespace)'],['../dd/d6a/rev_2fun_2accumulator_8hpp.html',1,'(Global Namespace)']]],
  ['acos_2ehpp_6313',['acos.hpp',['../df/d7d/fwd_2fun_2acos_8hpp.html',1,'(Global Namespace)'],['../d0/d07/opencl_2rev_2acos_8hpp.html',1,'(Global Namespace)'],['../de/d91/prim_2fun_2acos_8hpp.html',1,'(Global Namespace)'],['../d5/d30/rev_2fun_2acos_8hpp.html',1,'(Global Namespace)']]],
  ['acosh_2ehpp_6314',['acosh.hpp',['../d4/d31/fwd_2fun_2acosh_8hpp.html',1,'(Global Namespace)'],['../d2/d6b/opencl_2rev_2acosh_8hpp.html',1,'(Global Namespace)'],['../dd/db6/prim_2fun_2acosh_8hpp.html',1,'(Global Namespace)'],['../d1/d7e/rev_2fun_2acosh_8hpp.html',1,'(Global Namespace)']]],
  ['ad_5fpromotable_2ehpp_6315',['ad_promotable.hpp',['../de/d0d/ad__promotable_8hpp.html',1,'']]],
  ['add_2ehpp_6316',['add.hpp',['../d0/daf/opencl_2kernels_2add_8hpp.html',1,'(Global Namespace)'],['../d6/d5c/opencl_2rev_2add_8hpp.html',1,'(Global Namespace)'],['../d6/d15/prim_2fun_2add_8hpp.html',1,'(Global Namespace)']]],
  ['add_5fdiag_2ehpp_6317',['add_diag.hpp',['../d9/db3/opencl_2prim_2add__diag_8hpp.html',1,'(Global Namespace)'],['../d4/d58/opencl_2rev_2add__diag_8hpp.html',1,'(Global Namespace)'],['../d3/dda/prim_2fun_2add__diag_8hpp.html',1,'(Global Namespace)']]],
  ['add_5fnew_5fopencl_5fkernel_2emd_6318',['add_new_opencl_kernel.md',['../df/d89/add__new__opencl__kernel_8md.html',1,'']]],
  ['adding_5fnew_5fdistributions_2emd_6319',['adding_new_distributions.md',['../da/d3c/adding__new__distributions_8md.html',1,'']]],
  ['adjoint_5fof_2ehpp_6320',['adjoint_of.hpp',['../dc/dbd/adjoint__of_8hpp.html',1,'']]],
  ['adjoint_5fresults_2ehpp_6321',['adjoint_results.hpp',['../d6/d4c/adjoint__results_8hpp.html',1,'']]],
  ['algebra_5fsolver_5fadapter_2ehpp_6322',['algebra_solver_adapter.hpp',['../d3/d6a/algebra__solver__adapter_8hpp.html',1,'']]],
  ['algebra_5fsolver_5ffp_2ehpp_6323',['algebra_solver_fp.hpp',['../d4/d23/algebra__solver__fp_8hpp.html',1,'']]],
  ['algebra_5fsolver_5fnewton_2ehpp_6324',['algebra_solver_newton.hpp',['../d8/d28/algebra__solver__newton_8hpp.html',1,'']]],
  ['algebra_5fsolver_5fpowell_2ehpp_6325',['algebra_solver_powell.hpp',['../d7/d8e/algebra__solver__powell_8hpp.html',1,'']]],
  ['algebra_5fsystem_2ehpp_6326',['algebra_system.hpp',['../d3/d92/algebra__system_8hpp.html',1,'']]],
  ['append_2ehpp_6327',['append.hpp',['../d8/dc9/append_8hpp.html',1,'']]],
  ['append_5farray_2ehpp_6328',['append_array.hpp',['../df/ddd/opencl_2prim_2append__array_8hpp.html',1,'(Global Namespace)'],['../d3/db1/prim_2fun_2append__array_8hpp.html',1,'(Global Namespace)']]],
  ['append_5fcol_2ehpp_6329',['append_col.hpp',['../d0/d71/opencl_2rev_2append__col_8hpp.html',1,'(Global Namespace)'],['../d0/d49/prim_2fun_2append__col_8hpp.html',1,'(Global Namespace)'],['../dd/db4/rev_2fun_2append__col_8hpp.html',1,'(Global Namespace)']]],
  ['append_5freturn_5ftype_2ehpp_6330',['append_return_type.hpp',['../d1/d99/append__return__type_8hpp.html',1,'']]],
  ['append_5frow_2ehpp_6331',['append_row.hpp',['../d7/d94/opencl_2rev_2append__row_8hpp.html',1,'(Global Namespace)'],['../d4/d90/prim_2fun_2append__row_8hpp.html',1,'(Global Namespace)'],['../d1/d7d/rev_2fun_2append__row_8hpp.html',1,'(Global Namespace)']]],
  ['apply_2ehpp_6332',['apply.hpp',['../d7/d4c/apply_8hpp.html',1,'']]],
  ['apply_5fscalar_5fbinary_2ehpp_6333',['apply_scalar_binary.hpp',['../d4/d58/prim_2functor_2apply__scalar__binary_8hpp.html',1,'(Global Namespace)'],['../d4/d8c/rev_2functor_2apply__scalar__binary_8hpp.html',1,'(Global Namespace)']]],
  ['apply_5fscalar_5funary_2ehpp_6334',['apply_scalar_unary.hpp',['../dd/de2/fwd_2functor_2apply__scalar__unary_8hpp.html',1,'(Global Namespace)'],['../d1/d09/prim_2functor_2apply__scalar__unary_8hpp.html',1,'(Global Namespace)'],['../d6/d95/rev_2functor_2apply__scalar__unary_8hpp.html',1,'(Global Namespace)']]],
  ['apply_5fvector_5funary_2ehpp_6335',['apply_vector_unary.hpp',['../d7/d1b/prim_2functor_2apply__vector__unary_8hpp.html',1,'(Global Namespace)'],['../d2/d62/rev_2functor_2apply__vector__unary_8hpp.html',1,'(Global Namespace)']]],
  ['arena_5fallocator_2ehpp_6336',['arena_allocator.hpp',['../df/d8c/arena__allocator_8hpp.html',1,'']]],
  ['arena_5fmatrix_2ehpp_6337',['arena_matrix.hpp',['../d2/d8d/arena__matrix_8hpp.html',1,'']]],
  ['arena_5fmatrix_5fcl_2ehpp_6338',['arena_matrix_cl.hpp',['../df/de2/arena__matrix__cl_8hpp.html',1,'']]],
  ['arena_5ftype_2ehpp_6339',['arena_type.hpp',['../d1/d66/opencl_2rev_2arena__type_8hpp.html',1,'(Global Namespace)'],['../df/d66/rev_2meta_2arena__type_8hpp.html',1,'(Global Namespace)']]],
  ['arg_2ehpp_6340',['arg.hpp',['../d6/d7a/fwd_2fun_2arg_8hpp.html',1,'(Global Namespace)'],['../de/d27/prim_2fun_2arg_8hpp.html',1,'(Global Namespace)'],['../de/db4/rev_2fun_2arg_8hpp.html',1,'(Global Namespace)']]],
  ['array_5fbuilder_2ehpp_6341',['array_builder.hpp',['../d6/d17/array__builder_8hpp.html',1,'']]],
  ['as_5farray_5for_5fscalar_2ehpp_6342',['as_array_or_scalar.hpp',['../de/dfa/prim_2fun_2as__array__or__scalar_8hpp.html',1,'(Global Namespace)'],['../d5/d65/rev_2fun_2as__array__or__scalar_8hpp.html',1,'(Global Namespace)']]],
  ['as_5fbool_2ehpp_6343',['as_bool.hpp',['../d4/d9f/prim_2fun_2as__bool_8hpp.html',1,'(Global Namespace)'],['../dd/dd0/rev_2fun_2as__bool_8hpp.html',1,'(Global Namespace)']]],
  ['as_5fcolumn_5fvector_5for_5fscalar_2ehpp_6344',['as_column_vector_or_scalar.hpp',['../d7/d2b/opencl_2kernel__generator_2as__column__vector__or__scalar_8hpp.html',1,'(Global Namespace)'],['../d6/ded/opencl_2rev_2as__column__vector__or__scalar_8hpp.html',1,'(Global Namespace)'],['../d3/de4/prim_2fun_2as__column__vector__or__scalar_8hpp.html',1,'(Global Namespace)'],['../da/d10/rev_2fun_2as__column__vector__or__scalar_8hpp.html',1,'(Global Namespace)']]],
  ['as_5foperation_5fcl_2ehpp_6345',['as_operation_cl.hpp',['../d6/d7f/as__operation__cl_8hpp.html',1,'']]],
  ['as_5fvalue_5farray_5for_5fscalar_2ehpp_6346',['as_value_array_or_scalar.hpp',['../de/dd4/as__value__array__or__scalar_8hpp.html',1,'']]],
  ['as_5fvalue_5fcolumn_5farray_5for_5fscalar_2ehpp_6347',['as_value_column_array_or_scalar.hpp',['../d6/dcc/as__value__column__array__or__scalar_8hpp.html',1,'']]],
  ['as_5fvalue_5fcolumn_5fvector_5for_5fscalar_2ehpp_6348',['as_value_column_vector_or_scalar.hpp',['../d1/d72/as__value__column__vector__or__scalar_8hpp.html',1,'']]],
  ['asin_2ehpp_6349',['asin.hpp',['../d6/d1a/fwd_2fun_2asin_8hpp.html',1,'(Global Namespace)'],['../df/d06/opencl_2rev_2asin_8hpp.html',1,'(Global Namespace)'],['../d0/dff/prim_2fun_2asin_8hpp.html',1,'(Global Namespace)'],['../d8/d09/rev_2fun_2asin_8hpp.html',1,'(Global Namespace)']]],
  ['asinh_2ehpp_6350',['asinh.hpp',['../d3/dee/fwd_2fun_2asinh_8hpp.html',1,'(Global Namespace)'],['../d7/da7/opencl_2rev_2asinh_8hpp.html',1,'(Global Namespace)'],['../d3/d56/prim_2fun_2asinh_8hpp.html',1,'(Global Namespace)'],['../d1/d0e/rev_2fun_2asinh_8hpp.html',1,'(Global Namespace)']]],
  ['assign_2ehpp_6351',['assign.hpp',['../d2/dd7/assign_8hpp.html',1,'']]],
  ['atan_2ehpp_6352',['atan.hpp',['../d1/d9f/fwd_2fun_2atan_8hpp.html',1,'(Global Namespace)'],['../d3/d4d/opencl_2rev_2atan_8hpp.html',1,'(Global Namespace)'],['../d4/d88/prim_2fun_2atan_8hpp.html',1,'(Global Namespace)'],['../dd/d73/rev_2fun_2atan_8hpp.html',1,'(Global Namespace)']]],
  ['atan2_2ehpp_6353',['atan2.hpp',['../d9/de3/fwd_2fun_2atan2_8hpp.html',1,'(Global Namespace)'],['../de/d1f/prim_2fun_2atan2_8hpp.html',1,'(Global Namespace)'],['../d3/d4a/rev_2fun_2atan2_8hpp.html',1,'(Global Namespace)']]],
  ['atanh_2ehpp_6354',['atanh.hpp',['../de/d1b/fwd_2fun_2atanh_8hpp.html',1,'(Global Namespace)'],['../da/de0/opencl_2rev_2atanh_8hpp.html',1,'(Global Namespace)'],['../d9/d36/prim_2fun_2atanh_8hpp.html',1,'(Global Namespace)'],['../d3/d39/rev_2fun_2atanh_8hpp.html',1,'(Global Namespace)']]],
  ['atomic_5fadd_5fdouble_2ehpp_6355',['atomic_add_double.hpp',['../d9/dcd/atomic__add__double_8hpp.html',1,'']]],
  ['autocorrelation_2ehpp_6356',['autocorrelation.hpp',['../d1/d75/autocorrelation_8hpp.html',1,'']]],
  ['autocovariance_2ehpp_6357',['autocovariance.hpp',['../da/da5/autocovariance_8hpp.html',1,'']]],
  ['autodiff_5ftest_5fguide_2emd_6358',['autodiff_test_guide.md',['../d7/d01/autodiff__test__guide_8md.html',1,'']]],
  ['autodiffstackstorage_2ehpp_6359',['autodiffstackstorage.hpp',['../d6/daf/autodiffstackstorage_8hpp.html',1,'']]]
];
