var searchData=
[
  ['rank_2ehpp_7210',['rank.hpp',['../df/da5/opencl_2prim_2rank_8hpp.html',1,'(Global Namespace)'],['../dd/d00/prim_2fun_2rank_8hpp.html',1,'(Global Namespace)']]],
  ['rayleigh_5fccdf_5flog_2ehpp_7211',['rayleigh_ccdf_log.hpp',['../de/d5d/rayleigh__ccdf__log_8hpp.html',1,'']]],
  ['rayleigh_5fcdf_2ehpp_7212',['rayleigh_cdf.hpp',['../d5/d4f/opencl_2prim_2rayleigh__cdf_8hpp.html',1,'(Global Namespace)'],['../df/d0c/prim_2prob_2rayleigh__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['rayleigh_5fcdf_5flog_2ehpp_7213',['rayleigh_cdf_log.hpp',['../d0/d87/rayleigh__cdf__log_8hpp.html',1,'']]],
  ['rayleigh_5flccdf_2ehpp_7214',['rayleigh_lccdf.hpp',['../da/d85/opencl_2prim_2rayleigh__lccdf_8hpp.html',1,'(Global Namespace)'],['../d0/d4c/prim_2prob_2rayleigh__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['rayleigh_5flcdf_2ehpp_7215',['rayleigh_lcdf.hpp',['../d8/d65/opencl_2prim_2rayleigh__lcdf_8hpp.html',1,'(Global Namespace)'],['../dc/d9f/prim_2prob_2rayleigh__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['rayleigh_5flog_2ehpp_7216',['rayleigh_log.hpp',['../d2/dce/rayleigh__log_8hpp.html',1,'']]],
  ['rayleigh_5flpdf_2ehpp_7217',['rayleigh_lpdf.hpp',['../dc/de1/opencl_2prim_2rayleigh__lpdf_8hpp.html',1,'(Global Namespace)'],['../d1/db1/prim_2prob_2rayleigh__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['rayleigh_5frng_2ehpp_7218',['rayleigh_rng.hpp',['../de/dc8/rayleigh__rng_8hpp.html',1,'']]],
  ['read_5fcorr_5fl_2ehpp_7219',['read_corr_L.hpp',['../db/d5f/prim_2fun_2read__corr___l_8hpp.html',1,'(Global Namespace)'],['../d1/d7c/rev_2fun_2read__corr___l_8hpp.html',1,'(Global Namespace)']]],
  ['read_5fcorr_5fmatrix_2ehpp_7220',['read_corr_matrix.hpp',['../d0/dea/prim_2fun_2read__corr__matrix_8hpp.html',1,'(Global Namespace)'],['../d5/d2d/rev_2fun_2read__corr__matrix_8hpp.html',1,'(Global Namespace)']]],
  ['read_5fcov_5fl_2ehpp_7221',['read_cov_L.hpp',['../d5/d4a/prim_2fun_2read__cov___l_8hpp.html',1,'(Global Namespace)'],['../dd/d1d/rev_2fun_2read__cov___l_8hpp.html',1,'(Global Namespace)']]],
  ['read_5fcov_5fmatrix_2ehpp_7222',['read_cov_matrix.hpp',['../d0/d42/prim_2fun_2read__cov__matrix_8hpp.html',1,'(Global Namespace)'],['../de/d2e/rev_2fun_2read__cov__matrix_8hpp.html',1,'(Global Namespace)']]],
  ['read_5ffvar_2ehpp_7223',['read_fvar.hpp',['../d7/d66/read__fvar_8hpp.html',1,'']]],
  ['read_5fvar_2ehpp_7224',['read_var.hpp',['../d3/d1b/read__var_8hpp.html',1,'']]],
  ['readme_2emd_7225',['README.md',['../d9/dd6/_r_e_a_d_m_e_8md.html',1,'']]],
  ['real_2ehpp_7226',['real.hpp',['../d8/d23/real_8hpp.html',1,'']]],
  ['recover_5fmemory_2ehpp_7227',['recover_memory.hpp',['../d1/df9/recover__memory_8hpp.html',1,'']]],
  ['recover_5fmemory_5fnested_2ehpp_7228',['recover_memory_nested.hpp',['../da/d6e/recover__memory__nested_8hpp.html',1,'']]],
  ['reduce_5fsum_2ehpp_7229',['reduce_sum.hpp',['../d5/d99/fwd_2functor_2reduce__sum_8hpp.html',1,'(Global Namespace)'],['../d2/dfd/prim_2functor_2reduce__sum_8hpp.html',1,'(Global Namespace)'],['../db/d7a/rev_2functor_2reduce__sum_8hpp.html',1,'(Global Namespace)']]],
  ['reduce_5fsum_5fstatic_2ehpp_7230',['reduce_sum_static.hpp',['../db/dda/reduce__sum__static_8hpp.html',1,'']]],
  ['reduction_5f2d_2ehpp_7231',['reduction_2d.hpp',['../d4/dfe/reduction__2d_8hpp.html',1,'']]],
  ['ref_5ftype_2ehpp_7232',['ref_type.hpp',['../d4/d9b/opencl_2ref__type_8hpp.html',1,'(Global Namespace)'],['../d2/d93/prim_2meta_2ref__type_8hpp.html',1,'(Global Namespace)']]],
  ['ref_5ftype_5ffor_5fopencl_2ehpp_7233',['ref_type_for_opencl.hpp',['../d3/d02/ref__type__for__opencl_8hpp.html',1,'']]],
  ['rep_5farray_2ehpp_7234',['rep_array.hpp',['../db/d7c/opencl_2prim_2rep__array_8hpp.html',1,'(Global Namespace)'],['../d7/da9/prim_2fun_2rep__array_8hpp.html',1,'(Global Namespace)']]],
  ['rep_5fmatrix_2ehpp_7235',['rep_matrix.hpp',['../d7/d6d/opencl_2kernels_2rep__matrix_8hpp.html',1,'(Global Namespace)'],['../da/df2/opencl_2prim_2rep__matrix_8hpp.html',1,'(Global Namespace)'],['../da/da6/opencl_2rev_2rep__matrix_8hpp.html',1,'(Global Namespace)'],['../d4/d62/prim_2fun_2rep__matrix_8hpp.html',1,'(Global Namespace)'],['../d4/d21/rev_2fun_2rep__matrix_8hpp.html',1,'(Global Namespace)']]],
  ['rep_5frow_5fvector_2ehpp_7236',['rep_row_vector.hpp',['../dd/dc5/opencl_2prim_2rep__row__vector_8hpp.html',1,'(Global Namespace)'],['../db/d95/prim_2fun_2rep__row__vector_8hpp.html',1,'(Global Namespace)'],['../dc/dc3/rev_2fun_2rep__row__vector_8hpp.html',1,'(Global Namespace)']]],
  ['rep_5fvector_2ehpp_7237',['rep_vector.hpp',['../df/dcd/opencl_2prim_2rep__vector_8hpp.html',1,'(Global Namespace)'],['../d9/d2b/prim_2fun_2rep__vector_8hpp.html',1,'(Global Namespace)'],['../da/d2f/rev_2fun_2rep__vector_8hpp.html',1,'(Global Namespace)']]],
  ['require_5fgenerics_2ehpp_7238',['require_generics.hpp',['../d0/d02/require__generics_8hpp.html',1,'']]],
  ['require_5fhelpers_2ehpp_7239',['require_helpers.hpp',['../d2/dac/require__helpers_8hpp.html',1,'']]],
  ['resize_2ehpp_7240',['resize.hpp',['../dc/d12/resize_8hpp.html',1,'']]],
  ['return_5ftype_2ehpp_7241',['return_type.hpp',['../d9/d94/return__type_8hpp.html',1,'']]],
  ['return_5fvar_5fmatrix_2ehpp_7242',['return_var_matrix.hpp',['../dd/de3/return__var__matrix_8hpp.html',1,'']]],
  ['rev_2ehpp_7243',['rev.hpp',['../da/db7/opencl_2rev_8hpp.html',1,'(Global Namespace)'],['../d4/d64/rev_8hpp.html',1,'(Global Namespace)']]],
  ['rev_5fmatrix_5ftype_2ehpp_7244',['rev_matrix_type.hpp',['../d2/d0c/rev__matrix__type_8hpp.html',1,'']]],
  ['reverse_2ehpp_7245',['reverse.hpp',['../dd/d60/opencl_2prim_2reverse_8hpp.html',1,'(Global Namespace)'],['../d7/df5/opencl_2rev_2reverse_8hpp.html',1,'(Global Namespace)'],['../da/dfb/prim_2fun_2reverse_8hpp.html',1,'(Global Namespace)']]],
  ['reverse_5fmode_5ftypes_2emd_7246',['reverse_mode_types.md',['../d2/d5b/reverse__mode__types_8md.html',1,'']]],
  ['reverse_5fpass_5fcallback_2ehpp_7247',['reverse_pass_callback.hpp',['../d7/d2a/reverse__pass__callback_8hpp.html',1,'']]],
  ['rising_5ffactorial_2ehpp_7248',['rising_factorial.hpp',['../da/dcc/fwd_2fun_2rising__factorial_8hpp.html',1,'(Global Namespace)'],['../d0/d6b/prim_2fun_2rising__factorial_8hpp.html',1,'(Global Namespace)'],['../d8/d5b/rev_2fun_2rising__factorial_8hpp.html',1,'(Global Namespace)']]],
  ['round_2ehpp_7249',['round.hpp',['../d3/de9/fwd_2fun_2round_8hpp.html',1,'(Global Namespace)'],['../dc/d83/opencl_2rev_2round_8hpp.html',1,'(Global Namespace)'],['../d1/dfa/prim_2fun_2round_8hpp.html',1,'(Global Namespace)'],['../d5/da9/rev_2fun_2round_8hpp.html',1,'(Global Namespace)']]],
  ['row_2ehpp_7250',['row.hpp',['../d8/d8f/opencl_2prim_2row_8hpp.html',1,'(Global Namespace)'],['../d6/dc3/prim_2fun_2row_8hpp.html',1,'(Global Namespace)']]],
  ['rows_2ehpp_7251',['rows.hpp',['../de/dd4/opencl_2prim_2rows_8hpp.html',1,'(Global Namespace)'],['../d9/d86/prim_2fun_2rows_8hpp.html',1,'(Global Namespace)']]],
  ['rows_5fdot_5fproduct_2ehpp_7252',['rows_dot_product.hpp',['../df/db7/opencl_2prim_2rows__dot__product_8hpp.html',1,'(Global Namespace)'],['../d1/d0e/opencl_2rev_2rows__dot__product_8hpp.html',1,'(Global Namespace)'],['../d9/d21/prim_2fun_2rows__dot__product_8hpp.html',1,'(Global Namespace)'],['../d6/db4/rev_2fun_2rows__dot__product_8hpp.html',1,'(Global Namespace)']]],
  ['rows_5fdot_5fself_2ehpp_7253',['rows_dot_self.hpp',['../dc/d82/opencl_2prim_2rows__dot__self_8hpp.html',1,'(Global Namespace)'],['../de/d48/opencl_2rev_2rows__dot__self_8hpp.html',1,'(Global Namespace)'],['../d1/de3/prim_2fun_2rows__dot__self_8hpp.html',1,'(Global Namespace)'],['../d1/d9c/rev_2fun_2rows__dot__self_8hpp.html',1,'(Global Namespace)']]],
  ['rowwise_5freduction_2ehpp_7254',['rowwise_reduction.hpp',['../de/dc3/rowwise__reduction_8hpp.html',1,'']]]
];
