var searchData=
[
  ['tail_2ehpp_7353',['tail.hpp',['../db/d1f/opencl_2prim_2tail_8hpp.html',1,'(Global Namespace)'],['../d5/d0b/prim_2fun_2tail_8hpp.html',1,'(Global Namespace)']]],
  ['tan_2ehpp_7354',['tan.hpp',['../d3/d4c/fwd_2fun_2tan_8hpp.html',1,'(Global Namespace)'],['../d9/d65/opencl_2rev_2tan_8hpp.html',1,'(Global Namespace)'],['../d3/d22/prim_2fun_2tan_8hpp.html',1,'(Global Namespace)'],['../d2/d3b/rev_2fun_2tan_8hpp.html',1,'(Global Namespace)']]],
  ['tanh_2ehpp_7355',['tanh.hpp',['../d1/d45/fwd_2fun_2tanh_8hpp.html',1,'(Global Namespace)'],['../db/dfd/opencl_2rev_2tanh_8hpp.html',1,'(Global Namespace)'],['../d2/d5c/prim_2fun_2tanh_8hpp.html',1,'(Global Namespace)'],['../d2/dce/rev_2fun_2tanh_8hpp.html',1,'(Global Namespace)']]],
  ['tcrossprod_2ehpp_7356',['tcrossprod.hpp',['../d3/d6e/fwd_2fun_2tcrossprod_8hpp.html',1,'(Global Namespace)'],['../dd/dd8/opencl_2prim_2tcrossprod_8hpp.html',1,'(Global Namespace)'],['../de/d14/opencl_2rev_2tcrossprod_8hpp.html',1,'(Global Namespace)'],['../d6/d23/prim_2fun_2tcrossprod_8hpp.html',1,'(Global Namespace)'],['../de/d39/rev_2fun_2tcrossprod_8hpp.html',1,'(Global Namespace)']]],
  ['tgamma_2ehpp_7357',['tgamma.hpp',['../d5/d74/fwd_2fun_2tgamma_8hpp.html',1,'(Global Namespace)'],['../dd/dfc/opencl_2rev_2tgamma_8hpp.html',1,'(Global Namespace)'],['../d3/d8f/prim_2fun_2tgamma_8hpp.html',1,'(Global Namespace)'],['../d6/d29/rev_2fun_2tgamma_8hpp.html',1,'(Global Namespace)']]],
  ['threading_5ftbb_2emd_7358',['threading_tbb.md',['../d8/d53/threading__tbb_8md.html',1,'']]],
  ['throw_5fdomain_5ferror_2ehpp_7359',['throw_domain_error.hpp',['../d2/de6/throw__domain__error_8hpp.html',1,'']]],
  ['throw_5fdomain_5ferror_5fmat_2ehpp_7360',['throw_domain_error_mat.hpp',['../df/d7b/throw__domain__error__mat_8hpp.html',1,'']]],
  ['throw_5fdomain_5ferror_5fvec_2ehpp_7361',['throw_domain_error_vec.hpp',['../d8/dc6/throw__domain__error__vec_8hpp.html',1,'']]],
  ['to_5farena_2ehpp_7362',['to_arena.hpp',['../dc/d2c/opencl_2rev_2to__arena_8hpp.html',1,'(Global Namespace)'],['../dc/d4d/rev_2fun_2to__arena_8hpp.html',1,'(Global Namespace)']]],
  ['to_5farray_5f1d_2ehpp_7363',['to_array_1d.hpp',['../d5/d68/opencl_2prim_2to__array__1d_8hpp.html',1,'(Global Namespace)'],['../d0/de8/prim_2fun_2to__array__1d_8hpp.html',1,'(Global Namespace)']]],
  ['to_5farray_5f2d_2ehpp_7364',['to_array_2d.hpp',['../d4/d12/opencl_2prim_2to__array__2d_8hpp.html',1,'(Global Namespace)'],['../db/dc1/prim_2fun_2to__array__2d_8hpp.html',1,'(Global Namespace)']]],
  ['to_5fcomplex_2ehpp_7365',['to_complex.hpp',['../d1/dac/to__complex_8hpp.html',1,'']]],
  ['to_5ffvar_2ehpp_7366',['to_fvar.hpp',['../d6/d78/to__fvar_8hpp.html',1,'']]],
  ['to_5fmatrix_2ehpp_7367',['to_matrix.hpp',['../db/d80/opencl_2prim_2to__matrix_8hpp.html',1,'(Global Namespace)'],['../d6/d52/opencl_2rev_2to__matrix_8hpp.html',1,'(Global Namespace)'],['../d4/d6c/prim_2fun_2to__matrix_8hpp.html',1,'(Global Namespace)']]],
  ['to_5fref_2ehpp_7368',['to_ref.hpp',['../de/ddd/to__ref_8hpp.html',1,'']]],
  ['to_5fref_5ffor_5fopencl_2ehpp_7369',['to_ref_for_opencl.hpp',['../d1/d6e/to__ref__for__opencl_8hpp.html',1,'']]],
  ['to_5frow_5fvector_2ehpp_7370',['to_row_vector.hpp',['../de/d1f/opencl_2prim_2to__row__vector_8hpp.html',1,'(Global Namespace)'],['../da/df8/prim_2fun_2to__row__vector_8hpp.html',1,'(Global Namespace)']]],
  ['to_5fvar_2ehpp_7371',['to_var.hpp',['../d1/dd9/to__var_8hpp.html',1,'']]],
  ['to_5fvar_5fvalue_2ehpp_7372',['to_var_value.hpp',['../d9/dc4/to__var__value_8hpp.html',1,'']]],
  ['to_5fvector_2ehpp_7373',['to_vector.hpp',['../df/d15/opencl_2prim_2to__vector_8hpp.html',1,'(Global Namespace)'],['../d9/dd1/prim_2fun_2to__vector_8hpp.html',1,'(Global Namespace)'],['../d6/d37/rev_2fun_2to__vector_8hpp.html',1,'(Global Namespace)']]],
  ['trace_2ehpp_7374',['trace.hpp',['../d8/db1/opencl_2prim_2trace_8hpp.html',1,'(Global Namespace)'],['../df/de3/opencl_2rev_2trace_8hpp.html',1,'(Global Namespace)'],['../d1/d3a/prim_2fun_2trace_8hpp.html',1,'(Global Namespace)'],['../dc/d5a/rev_2fun_2trace_8hpp.html',1,'(Global Namespace)']]],
  ['trace_5fgen_5finv_5fquad_5fform_5fldlt_2ehpp_7375',['trace_gen_inv_quad_form_ldlt.hpp',['../d2/da3/prim_2fun_2trace__gen__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)'],['../d0/de2/rev_2fun_2trace__gen__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)']]],
  ['trace_5fgen_5fquad_5fform_2ehpp_7376',['trace_gen_quad_form.hpp',['../d2/d2d/prim_2fun_2trace__gen__quad__form_8hpp.html',1,'(Global Namespace)'],['../d3/d73/rev_2fun_2trace__gen__quad__form_8hpp.html',1,'(Global Namespace)']]],
  ['trace_5finv_5fquad_5fform_5fldlt_2ehpp_7377',['trace_inv_quad_form_ldlt.hpp',['../d3/de3/prim_2fun_2trace__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)'],['../d4/dae/rev_2fun_2trace__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)']]],
  ['trace_5fquad_5fform_2ehpp_7378',['trace_quad_form.hpp',['../da/d3a/fwd_2fun_2trace__quad__form_8hpp.html',1,'(Global Namespace)'],['../de/d9c/prim_2fun_2trace__quad__form_8hpp.html',1,'(Global Namespace)'],['../d9/dd4/rev_2fun_2trace__quad__form_8hpp.html',1,'(Global Namespace)']]],
  ['transpose_2ehpp_7379',['transpose.hpp',['../d9/de7/opencl_2kernel__generator_2transpose_8hpp.html',1,'(Global Namespace)'],['../d6/d1c/opencl_2rev_2transpose_8hpp.html',1,'(Global Namespace)'],['../dd/d7a/prim_2fun_2transpose_8hpp.html',1,'(Global Namespace)']]],
  ['tri_5finverse_2ehpp_7380',['tri_inverse.hpp',['../d4/dfb/tri__inverse_8hpp.html',1,'']]],
  ['tridiagonalization_2ehpp_7381',['tridiagonalization.hpp',['../d4/dae/kernels_2tridiagonalization_8hpp.html',1,'(Global Namespace)'],['../dc/d19/tridiagonalization_8hpp.html',1,'(Global Namespace)']]],
  ['trigamma_2ehpp_7382',['trigamma.hpp',['../d6/dd6/fwd_2fun_2trigamma_8hpp.html',1,'(Global Namespace)'],['../d3/dd4/opencl_2kernels_2device__functions_2trigamma_8hpp.html',1,'(Global Namespace)'],['../d5/d0c/prim_2fun_2trigamma_8hpp.html',1,'(Global Namespace)'],['../d0/dca/rev_2fun_2trigamma_8hpp.html',1,'(Global Namespace)']]],
  ['trunc_2ehpp_7383',['trunc.hpp',['../d3/d10/fwd_2fun_2trunc_8hpp.html',1,'(Global Namespace)'],['../d9/d21/opencl_2rev_2trunc_8hpp.html',1,'(Global Namespace)'],['../d0/d91/prim_2fun_2trunc_8hpp.html',1,'(Global Namespace)'],['../d5/dcb/rev_2fun_2trunc_8hpp.html',1,'(Global Namespace)']]],
  ['type_5fstr_2ehpp_7384',['type_str.hpp',['../d6/d6c/type__str_8hpp.html',1,'']]],
  ['typedefs_2ehpp_7385',['typedefs.hpp',['../d2/d80/fwd_2fun_2typedefs_8hpp.html',1,'(Global Namespace)'],['../dd/d5f/mix_2fun_2typedefs_8hpp.html',1,'(Global Namespace)'],['../d1/d29/prim_2fun_2typedefs_8hpp.html',1,'(Global Namespace)'],['../dd/db1/rev_2core_2typedefs_8hpp.html',1,'(Global Namespace)']]]
];
