var searchData=
[
  ['gamma_5fccdf_5flog_2ehpp_6675',['gamma_ccdf_log.hpp',['../d2/d5e/gamma__ccdf__log_8hpp.html',1,'']]],
  ['gamma_5fcdf_2ehpp_6676',['gamma_cdf.hpp',['../d0/d51/gamma__cdf_8hpp.html',1,'']]],
  ['gamma_5fcdf_5flog_2ehpp_6677',['gamma_cdf_log.hpp',['../d1/dbb/gamma__cdf__log_8hpp.html',1,'']]],
  ['gamma_5flccdf_2ehpp_6678',['gamma_lccdf.hpp',['../dd/d51/gamma__lccdf_8hpp.html',1,'']]],
  ['gamma_5flcdf_2ehpp_6679',['gamma_lcdf.hpp',['../d1/d1c/gamma__lcdf_8hpp.html',1,'']]],
  ['gamma_5flog_2ehpp_6680',['gamma_log.hpp',['../d9/d76/gamma__log_8hpp.html',1,'']]],
  ['gamma_5flpdf_2ehpp_6681',['gamma_lpdf.hpp',['../df/d44/opencl_2prim_2gamma__lpdf_8hpp.html',1,'(Global Namespace)'],['../d2/d93/prim_2prob_2gamma__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['gamma_5fp_2ehpp_6682',['gamma_p.hpp',['../d6/d8c/fwd_2fun_2gamma__p_8hpp.html',1,'(Global Namespace)'],['../da/dc0/prim_2fun_2gamma__p_8hpp.html',1,'(Global Namespace)'],['../d3/d0a/rev_2fun_2gamma__p_8hpp.html',1,'(Global Namespace)']]],
  ['gamma_5fq_2ehpp_6683',['gamma_q.hpp',['../d7/d10/fwd_2fun_2gamma__q_8hpp.html',1,'(Global Namespace)'],['../da/d7d/prim_2fun_2gamma__q_8hpp.html',1,'(Global Namespace)'],['../d1/deb/rev_2fun_2gamma__q_8hpp.html',1,'(Global Namespace)']]],
  ['gamma_5frng_2ehpp_6684',['gamma_rng.hpp',['../d0/d5b/gamma__rng_8hpp.html',1,'']]],
  ['gaussian_5fdlm_5fobs_5flog_2ehpp_6685',['gaussian_dlm_obs_log.hpp',['../dd/ddd/gaussian__dlm__obs__log_8hpp.html',1,'']]],
  ['gaussian_5fdlm_5fobs_5flpdf_2ehpp_6686',['gaussian_dlm_obs_lpdf.hpp',['../db/d67/gaussian__dlm__obs__lpdf_8hpp.html',1,'']]],
  ['gaussian_5fdlm_5fobs_5frng_2ehpp_6687',['gaussian_dlm_obs_rng.hpp',['../db/ddb/gaussian__dlm__obs__rng_8hpp.html',1,'']]],
  ['generalized_5finverse_2ehpp_6688',['generalized_inverse.hpp',['../df/d21/prim_2fun_2generalized__inverse_8hpp.html',1,'(Global Namespace)'],['../d8/d25/rev_2fun_2generalized__inverse_8hpp.html',1,'(Global Namespace)']]],
  ['get_2ehpp_6689',['get.hpp',['../dc/d95/get_8hpp.html',1,'']]],
  ['get_5fbase1_2ehpp_6690',['get_base1.hpp',['../d9/d65/get__base1_8hpp.html',1,'']]],
  ['get_5fbase1_5flhs_2ehpp_6691',['get_base1_lhs.hpp',['../d2/d77/get__base1__lhs_8hpp.html',1,'']]],
  ['get_5fimag_2ehpp_6692',['get_imag.hpp',['../dd/dcc/get__imag_8hpp.html',1,'']]],
  ['get_5fkernel_5fsource_5ffor_5fevaluating_5finto_2ehpp_6693',['get_kernel_source_for_evaluating_into.hpp',['../d0/de2/get__kernel__source__for__evaluating__into_8hpp.html',1,'']]],
  ['get_5flp_2ehpp_6694',['get_lp.hpp',['../da/d74/get__lp_8hpp.html',1,'']]],
  ['get_5freal_2ehpp_6695',['get_real.hpp',['../d8/d11/get__real_8hpp.html',1,'']]],
  ['getting_5fstarted_2emd_6696',['getting_started.md',['../d7/de9/getting__started_8md.html',1,'']]],
  ['gevv_5fvvv_5fvari_2ehpp_6697',['gevv_vvv_vari.hpp',['../d8/de0/gevv__vvv__vari_8hpp.html',1,'']]],
  ['gp_5fdot_5fprod_5fcov_2ehpp_6698',['gp_dot_prod_cov.hpp',['../d9/d83/opencl_2prim_2gp__dot__prod__cov_8hpp.html',1,'(Global Namespace)'],['../d6/dbd/prim_2fun_2gp__dot__prod__cov_8hpp.html',1,'(Global Namespace)']]],
  ['gp_5fexp_5fquad_5fcov_2ehpp_6699',['gp_exp_quad_cov.hpp',['../d6/df0/opencl_2kernels_2gp__exp__quad__cov_8hpp.html',1,'(Global Namespace)'],['../d9/dcc/opencl_2prim_2gp__exp__quad__cov_8hpp.html',1,'(Global Namespace)'],['../d3/d88/prim_2fun_2gp__exp__quad__cov_8hpp.html',1,'(Global Namespace)'],['../d6/d16/rev_2fun_2gp__exp__quad__cov_8hpp.html',1,'(Global Namespace)']]],
  ['gp_5fexponential_5fcov_2ehpp_6700',['gp_exponential_cov.hpp',['../df/d14/opencl_2kernels_2gp__exponential__cov_8hpp.html',1,'(Global Namespace)'],['../d3/d20/opencl_2prim_2gp__exponential__cov_8hpp.html',1,'(Global Namespace)'],['../db/dac/prim_2fun_2gp__exponential__cov_8hpp.html',1,'(Global Namespace)']]],
  ['gp_5fmatern32_5fcov_2ehpp_6701',['gp_matern32_cov.hpp',['../de/db2/opencl_2kernels_2gp__matern32__cov_8hpp.html',1,'(Global Namespace)'],['../d6/d8d/opencl_2prim_2gp__matern32__cov_8hpp.html',1,'(Global Namespace)'],['../d4/d9c/prim_2fun_2gp__matern32__cov_8hpp.html',1,'(Global Namespace)']]],
  ['gp_5fmatern52_5fcov_2ehpp_6702',['gp_matern52_cov.hpp',['../df/d4b/opencl_2kernels_2gp__matern52__cov_8hpp.html',1,'(Global Namespace)'],['../d8/df9/opencl_2prim_2gp__matern52__cov_8hpp.html',1,'(Global Namespace)'],['../da/d46/prim_2fun_2gp__matern52__cov_8hpp.html',1,'(Global Namespace)']]],
  ['gp_5fperiodic_5fcov_2ehpp_6703',['gp_periodic_cov.hpp',['../df/dd0/prim_2fun_2gp__periodic__cov_8hpp.html',1,'(Global Namespace)'],['../da/dbc/rev_2fun_2gp__periodic__cov_8hpp.html',1,'(Global Namespace)']]],
  ['grad_2ehpp_6704',['grad.hpp',['../d8/dc8/core_2grad_8hpp.html',1,'(Global Namespace)'],['../db/df5/fun_2grad_8hpp.html',1,'(Global Namespace)']]],
  ['grad_5f2f1_2ehpp_6705',['grad_2F1.hpp',['../dd/d28/grad__2_f1_8hpp.html',1,'']]],
  ['grad_5ff32_2ehpp_6706',['grad_F32.hpp',['../df/dff/grad___f32_8hpp.html',1,'']]],
  ['grad_5fhessian_2ehpp_6707',['grad_hessian.hpp',['../d0/d20/grad__hessian_8hpp.html',1,'']]],
  ['grad_5finc_5fbeta_2ehpp_6708',['grad_inc_beta.hpp',['../d1/dcb/fwd_2fun_2grad__inc__beta_8hpp.html',1,'(Global Namespace)'],['../d5/d46/prim_2fun_2grad__inc__beta_8hpp.html',1,'(Global Namespace)'],['../db/d43/rev_2fun_2grad__inc__beta_8hpp.html',1,'(Global Namespace)']]],
  ['grad_5freg_5finc_5fbeta_2ehpp_6709',['grad_reg_inc_beta.hpp',['../df/d04/grad__reg__inc__beta_8hpp.html',1,'']]],
  ['grad_5freg_5finc_5fgamma_2ehpp_6710',['grad_reg_inc_gamma.hpp',['../db/d7d/grad__reg__inc__gamma_8hpp.html',1,'']]],
  ['grad_5freg_5flower_5finc_5fgamma_2ehpp_6711',['grad_reg_lower_inc_gamma.hpp',['../d3/de2/grad__reg__lower__inc__gamma_8hpp.html',1,'']]],
  ['grad_5ftr_5fmat_5ftimes_5fhessian_2ehpp_6712',['grad_tr_mat_times_hessian.hpp',['../dc/d21/grad__tr__mat__times__hessian_8hpp.html',1,'']]],
  ['gradient_2ehpp_6713',['gradient.hpp',['../d6/d7d/fwd_2functor_2gradient_8hpp.html',1,'(Global Namespace)'],['../d0/d5a/rev_2functor_2gradient_8hpp.html',1,'(Global Namespace)']]],
  ['gradient_5fdot_5fvector_2ehpp_6714',['gradient_dot_vector.hpp',['../d7/dd9/gradient__dot__vector_8hpp.html',1,'']]],
  ['gumbel_5fccdf_5flog_2ehpp_6715',['gumbel_ccdf_log.hpp',['../da/ddd/gumbel__ccdf__log_8hpp.html',1,'']]],
  ['gumbel_5fcdf_2ehpp_6716',['gumbel_cdf.hpp',['../d1/df2/opencl_2prim_2gumbel__cdf_8hpp.html',1,'(Global Namespace)'],['../d6/ddf/prim_2prob_2gumbel__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['gumbel_5fcdf_5flog_2ehpp_6717',['gumbel_cdf_log.hpp',['../dd/dd2/gumbel__cdf__log_8hpp.html',1,'']]],
  ['gumbel_5flccdf_2ehpp_6718',['gumbel_lccdf.hpp',['../de/d8c/opencl_2prim_2gumbel__lccdf_8hpp.html',1,'(Global Namespace)'],['../da/d40/prim_2prob_2gumbel__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['gumbel_5flcdf_2ehpp_6719',['gumbel_lcdf.hpp',['../d2/da0/opencl_2prim_2gumbel__lcdf_8hpp.html',1,'(Global Namespace)'],['../d3/d5e/prim_2prob_2gumbel__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['gumbel_5flog_2ehpp_6720',['gumbel_log.hpp',['../d1/d24/gumbel__log_8hpp.html',1,'']]],
  ['gumbel_5flpdf_2ehpp_6721',['gumbel_lpdf.hpp',['../d3/d6f/opencl_2prim_2gumbel__lpdf_8hpp.html',1,'(Global Namespace)'],['../dd/dad/prim_2prob_2gumbel__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['gumbel_5frng_2ehpp_6722',['gumbel_rng.hpp',['../de/ddf/gumbel__rng_8hpp.html',1,'']]]
];
